/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuildInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildInfo{}

// BuildInfo Distribution metadata for this deployed build.
type BuildInfo struct {
	// Distribution name for this deployment
	Distribution string `json:"distribution"`
	// Upstream repository this build is based on
	UpstreamRepository string `json:"upstream_repository"`
	// Upstream release version this build is based on
	UpstreamVersion string `json:"upstream_version"`
}

type _BuildInfo BuildInfo

// NewBuildInfo instantiates a new BuildInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildInfo(distribution string, upstreamRepository string, upstreamVersion string) *BuildInfo {
	this := BuildInfo{}
	this.Distribution = distribution
	this.UpstreamRepository = upstreamRepository
	this.UpstreamVersion = upstreamVersion
	return &this
}

// NewBuildInfoWithDefaults instantiates a new BuildInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildInfoWithDefaults() *BuildInfo {
	this := BuildInfo{}
	return &this
}

// GetDistribution returns the Distribution field value
func (o *BuildInfo) GetDistribution() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value
// and a boolean to check if the value has been set.
func (o *BuildInfo) GetDistributionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Distribution, true
}

// SetDistribution sets field value
func (o *BuildInfo) SetDistribution(v string) {
	o.Distribution = v
}

// GetUpstreamRepository returns the UpstreamRepository field value
func (o *BuildInfo) GetUpstreamRepository() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpstreamRepository
}

// GetUpstreamRepositoryOk returns a tuple with the UpstreamRepository field value
// and a boolean to check if the value has been set.
func (o *BuildInfo) GetUpstreamRepositoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpstreamRepository, true
}

// SetUpstreamRepository sets field value
func (o *BuildInfo) SetUpstreamRepository(v string) {
	o.UpstreamRepository = v
}

// GetUpstreamVersion returns the UpstreamVersion field value
func (o *BuildInfo) GetUpstreamVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpstreamVersion
}

// GetUpstreamVersionOk returns a tuple with the UpstreamVersion field value
// and a boolean to check if the value has been set.
func (o *BuildInfo) GetUpstreamVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpstreamVersion, true
}

// SetUpstreamVersion sets field value
func (o *BuildInfo) SetUpstreamVersion(v string) {
	o.UpstreamVersion = v
}

func (o BuildInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["distribution"] = o.Distribution
	toSerialize["upstream_repository"] = o.UpstreamRepository
	toSerialize["upstream_version"] = o.UpstreamVersion
	return toSerialize, nil
}

func (o *BuildInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"distribution",
		"upstream_repository",
		"upstream_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildInfo := _BuildInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildInfo)

	if err != nil {
		return err
	}

	*o = BuildInfo(varBuildInfo)

	return err
}

type NullableBuildInfo struct {
	value *BuildInfo
	isSet bool
}

func (v NullableBuildInfo) Get() *BuildInfo {
	return v.value
}

func (v *NullableBuildInfo) Set(val *BuildInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildInfo(val *BuildInfo) *NullableBuildInfo {
	return &NullableBuildInfo{value: val, isSet: true}
}

func (v NullableBuildInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


